language: node_js
node_js:
  - stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g typings
  - npm install -g codeclimate-test-reporter
  - typings install
script: node_modules/karma/bin/karma start karma.conf.js --single-run
after_success:
  - codeclimate-test-reporter < coverage/lcov.info
addons:
  code_climate:
    repo_token: ae685449cff9c41cc95750ef94f121c59c98d6c783537bff73e26b0afc6f125f
